Update Testes Regressivos API Pet Store.yml

diff --git a/.github/workflows/Testes Regressivos API Pet Store.yml b/.github/workflows/Testes Regressivos API Pet Store.yml
--- a/.github/workflows/Testes Regressivos API Pet Store.yml
+++ b/.github/workflows/Testes Regressivos API Pet Store.yml
@@ -51,9 +51,12 @@ jobs:
         id: extract_logs
         run: |
           echo "Extraindo logs de erro..."
-          if [ -f output/allure/log.html ]; then
+          # Define o caminho do arquivo de log
+          LOG_FILE='/home/runner/work/RobotExemploPetStore/RobotExemploPetStore/output/allure/log.html'
+          
+          if [ -f "$LOG_FILE" ]; then
             # Extrair logs de erro contendo a palavra "FAIL"
-            grep -A 20 'FAIL' output/allure/log.html > output/allure/error_log.txt || echo "Não foram encontrados erros no log."
+            grep -A 20 'FAIL' "$LOG_FILE" > output/allure/error_log.txt || echo "Não foram encontrados erros no log."
           else
             echo "Arquivo log.html não encontrado." > output/allure/error_log.txt
           fi
@@ -62,8 +65,8 @@ jobs:
         if: always()  # Sempre executa, independentemente do sucesso ou falha
         run: |
           echo "Verificando logs..."
-          ls -l output/allure/
-          cat output/allure/log.html || echo "log.html não encontrado."
+          ls -l /home/runner/work/RobotExemploPetStore/RobotExemploPetStore/output/allure/
+          cat /home/runner/work/RobotExemploPetStore/RobotExemploPetStore/output/allure/log.html || echo "log.html não encontrado."
           cat output/allure/error_log.txt || echo "error_log.txt não encontrado."
 
       - name: Create Issue if Tests Fail
