Update Testes Regressivos API Pet Store.yml

diff --git a/.github/workflows/Testes Regressivos API Pet Store.yml b/.github/workflows/Testes Regressivos API Pet Store.yml
--- a/.github/workflows/Testes Regressivos API Pet Store.yml
+++ b/.github/workflows/Testes Regressivos API Pet Store.yml
@@ -48,17 +48,25 @@ jobs:
         continue-on-error: true  # Continua o fluxo mesmo se falhar
 
       - name: Extract Error Logs
+        id: extract_logs
         if: failure()
         run: |
-          # Extrair o log de erro diretamente
           if [ -f output/allure/log.html ]; then
             grep -A 20 '<div class="error">' output/allure/log.html > output/allure/error_log.txt || echo "Não foram encontrados erros no log."
           else
             echo "Arquivo log.html não encontrado." > output/allure/error_log.txt
           fi
 
+      - name: Debug Log Output
+        if: always()  # Sempre executa, independentemente do sucesso ou falha
+        run: |
+          echo "Test logs:"
+          ls -l output/allure/
+          cat output/allure/log.html || echo "log.html não encontrado."
+          cat output/allure/error_log.txt || echo "error_log.txt não encontrado."
+
       - name: Create Issue if Tests Fail
-        if: failure()
+        if: failure()  # Somente cria a issue se houver falha
         uses: actions/github-script@v3
         with:
           script: |
